name: C/C++ CI

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: cmake
      run: 
        mkdir -p build
        cd build
        cmake ..
        make
